### ISSUE TITLE
Compatibility Request

### ISSUE THREAD

**Issue by epicmusic42** [erithtotl/FVTT-Wall-Height#8]
If compatibility with the module Perfect Vision could be made possible that would be awesome! Running PF1 I kinda need Perfect Vision for darkvision to work.

**Comment by erithtotl** [comment]
What happens when you run them both?  Perfect Vision is a much more complex module than wall-height, but I had hoped I'd eliminated any compatibility issues

**Comment by epicmusic42** [comment]
It just acts like a normal wall. raising a token to be above or below the wall doesn't let them see past it. as far as i've been able to tell, there's no difference in how the wall effects their vision than if i turn wall heights off.

**Comment by erithtotl** [comment]
Turning on Tokenvision doesn't break wall height for me, I just tested it.

I have released an update with some bug fixes.  In case it was possibly one of the other issues please try with the latest update and let me know.

**Comment by epicmusic42** [comment]
it looks like the latest update did fix it! thank you v much!

**Comment by QuentinLeCaignec** [comment]
I still have issues with Perfect Vision + Wall Height, specifically with "Limited" vision on walls (terrain walls).

Example problem: A character 1 is facing a terrain wall (infinity height), behind is an enemy 2, and behind the enemy is another terrain wall (infinity height).
The walls function fine for the map (I can see beyond the first terrain wall but not the second), but I can't see the enemy 2 token behind the first wall (even though my vision shows that part of the map).

This makes it basically impossible to use terrain walls with this combination of mods for me, since even just one terrain wall makes every token behind it invisible.

**Comment by baileywick** [comment]
Same problem here.

**Comment by erithtotl** [comment]
I'll play around with this tomorrow.  I've never spent much time looking into how the game processes terrain walls so this should be interesting.
